stages:
  - lint
  - test
  - build
  - push
  - release

include:
  - project: shared/gitlab-templates
    file:
      # - Jobs/Build.gitlab-ci.yml
      - golang.yml

.go-cache:
  variables:
    KUBERNETES_HELPER_MEMORY_LIMIT: 256Mi
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi

goreleaser:build:
  image:
    name: goreleaser/goreleaser:nightly
    entrypoint: [""]

goreleaser:release:github:
  extends: "goreleaser:release"
  id_tokens:
    VAULT_ID_TOKEN:
      aud: https://vault.office.ottonova.de
  secrets:
    GITHUB_TOKEN:
      vault: ci/terraform/GITHUB_USER_PAT_CLASSIC/value@secret
      file: false
  image:
    name: goreleaser/goreleaser:nightly
    entrypoint: [""]
  script:
    - goreleaser release --config .goreleaser.github.yml
