# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

# Gitlab config
gitlab_urls:
  api: https://gitlab.on.ag/api/v4/
  download: https://gitlab.on.ag

  # set to true if you use a self-signed certificate
  skip_tls_verify: false

  # set to true if you want to upload to the Package Registry rather than attachments
  use_package_registry: true

  # Set this if you set GITLAB_TOKEN to the value of CI_JOB_TOKEN.
  use_job_token: true

github_urls:
  api: https://api.github.com/
  upload: https://uploads.github.com/
  download: https://github.com/

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Releaser config
builds:
  - main: ./cmd/main.go
    binary: "{{.ProjectName}}"
    flags:
      - -v
    ldflags:
      - -s -w -extldflags '-static' -X gitlab.on.ag/shared/software/tflint-ruleset-csc26/internal/app/version.Version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: "debug-build"
    main: ./cmd/main.go
    binary: "debug-{{.ProjectName}}"
    flags:
      - -v
    gcflags:
      - all=-N -l
    ldflags:
      - -X gitlab.on.ag/shared/software/tflint-ruleset-csc26/internal/app/version.Version=v{{.Version}}
    tags:
      - debug
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
    no_unique_dist_dir: true

universal_binaries:
  - replace: true

archives:
  - formats:
      - tar.gz
      - zip
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - Merge branch

release:
  github:
    owner: ottonova
    name: tflint-ruleset-csc26

  name_template: "{{ .ProjectName }} v{{.Version}}"
  header: |
    Welcome to the latest release of {{ title .ProjectName}}!
