version: 2
registries:
  gitlab-registry: 
    type: docker-registry
    url: registry.on.ag
    username: ${{ON_GITLAB_REGISTRY_USERNAME}}
    password: ${{ON_GITLAB_REGISTRY_PASSWORD}}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "max.walther"
      - "patrick.pfenning"
    assignees:
      - "patrick.pfenning"
    pull-request-branch-name:
      separator: /
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "max.walther"
      - "patrick.pfenning"
    assignees:
      - "patrick.pfenning"
    pull-request-branch-name:
      separator: /
